name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Debug npm and node versions
      run: |
        npm --version
        node --version

    - name: Verify Docker installation
      run: |
        docker --version
        docker info

    - name: Check for Docker-related changes
      id: docker-changes
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'docker/' && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"

    - name: Build Docker image if changed
      if: steps.docker-changes.outputs.changed == 'true'
      run: |
        chmod +x ./manage.sh
        ./manage.sh rebuild

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull pre-built Docker image if no changes
      if: steps.docker-changes.outputs.changed != 'true'
      run: |
        docker pull softfl0w/llm-agent-env:latest
        docker run -d --name llm-agent-container -p 6668:6668 -p 3010:3000 -p 2222:22 softfl0w/llm-agent-env:latest

    - name: Install dependencies
      run: |
        cd tests
        npm --verbose ci

    - name: Run E2E tests headlessly
      run: ./manage.sh test

    - name: Debug Docker container
      if: failure()
      run: |
        docker logs llm-agent-container

    - name: Push new Docker image if built
      if: steps.docker-changes.outputs.changed == 'true' && success()
      run: |
        docker tag llm-agent-env:latest softfl0w/llm-agent-env:latest
        docker push softfl0w/llm-agent-env:latest
